// DNA -> design tokens: CSS variables, Tailwind v4 @theme, Tailwind v3 preset, DTCG JSON, component CSS.
import { googleFontsUrl } from '../lib/fonts.js';

const q = (name) => (/\s/.test(name) ? `"${name}"` : name);
const fontStack = (f) => (f ? `${q(f.use || f.name)}, ${f.fallback}` : 'ui-sans-serif, system-ui, sans-serif');
const em = (v) => `${Math.round((v || 0) * 1000) / 1000}em`;

/** Flat token map shared by every output format. Keys follow Tailwind v4 namespaces. */
export function tokenMap(dna) {
  const c = dna.color, t = dna.typography, s = dna.spacing;
  const tokens = {};
  for (const [k, v] of Object.entries(c.roles)) tokens[`color-${k}`] = v;
  for (const [rampName, steps] of Object.entries(c.ramps)) for (const [step, v] of Object.entries(steps)) tokens[`color-${rampName}-${step}`] = v;
  tokens['font-display'] = fontStack(t.families.display);
  tokens['font-body'] = fontStack(t.families.body);
  tokens['font-sans'] = tokens['font-body'];
  if (t.families.ui) tokens['font-ui'] = fontStack(t.families.ui);
  if (t.families.mono) tokens['font-mono'] = fontStack(t.families.mono);
  for (const [k, v] of Object.entries(t.scale)) tokens[`text-${k}`] = `${v / 16}rem`;
  tokens['font-weight-body'] = String(t.body.weight);
  tokens['font-weight-heading'] = String(t.headings.h2.weight || t.headings.h1.weight);
  tokens['font-weight-display'] = String(t.headings.h1.weight);
  tokens['leading-body'] = String(t.body.lineHeight);
  tokens['leading-heading'] = String(t.headings.h2.lineHeight || 1.2);
  tokens['leading-display'] = String(t.headings.h1.lineHeight || 1.1);
  tokens['tracking-display'] = em(t.headings.h1.letterSpacing);
  tokens['tracking-heading'] = em(t.headings.h2.letterSpacing);
  if (t.eyebrow) tokens['tracking-eyebrow'] = em(t.eyebrow.letterSpacing);
  tokens.spacing = `${s.unit / 16}rem`;
  s.scale.forEach((v, i) => { tokens[`space-${i + 1}`] = `${v / 16}rem`; });
  tokens['section-y'] = `${s.sectionY / 16}rem`;
  tokens['container'] = `${s.container}px`;
  tokens['gutter'] = `${s.gutter}px`;
  for (const [k, v] of Object.entries(dna.shape.radius)) tokens[`radius-${k}`] = v >= 9999 ? '9999px' : `${v}px`;
  for (const [k, v] of Object.entries(dna.elevation.shadows || {})) tokens[`shadow-${k}`] = v;
  tokens['duration'] = `${dna.motion.duration}ms`;
  tokens['ease-brand'] = dna.motion.easing;
  if (dna.color.gradients?.[0]) tokens['gradient-brand'] = dna.color.gradients[0];
  return tokens;
}

const header = (dna) => `/* Design DNA "${dna.name}" — generated by design-cloner. Personality: ${dna.personality.keywords.join(', ')} */`;

export function fontImport(dna) {
  const f = dna.typography.families;
  const url = googleFontsUrl([f.display, f.body, f.ui, f.mono].filter(Boolean));
  return url ? `@import url('${url}');\n` : '';
}

export function toCss(dna) {
  const tokens = tokenMap(dna);
  const lines = Object.entries(tokens).map(([k, v]) => `  --${k}: ${v};`);
  return `${header(dna)}\n${fontImport(dna)}\n:root {\n  color-scheme: ${dna.color.mode};\n${lines.join('\n')}\n}\n`;
}

export function toTailwindV4(dna) {
  const tokens = tokenMap(dna);
  const skip = new Set(['section-y', 'container', 'gutter', 'duration', 'gradient-brand']);
  const theme = Object.entries(tokens).filter(([k]) => !skip.has(k) && !k.startsWith('space-')).map(([k, v]) => `  --${k}: ${v};`);
  const extra = Object.entries(tokens).filter(([k]) => skip.has(k) || k.startsWith('space-')).map(([k, v]) => `  --${k}: ${v};`);
  return `${header(dna)}\n/* Tailwind CSS v4: @import "tailwindcss"; then @import "./tailwind-v4.css"; */\n${fontImport(dna)}\n@theme {\n${theme.join('\n')}\n}\n\n:root {\n${extra.join('\n')}\n}\n`;
}

export function toTailwindPreset(dna) {
  const c = dna.color, t = dna.typography;
  const colors = {};
  for (const [k, v] of Object.entries(c.roles)) colors[k] = v;
  for (const [name, steps] of Object.entries(c.ramps)) colors[name] = { ...steps, DEFAULT: c.roles[name] || steps[500] };
  const fontSize = Object.fromEntries(Object.entries(t.scale).map(([k, v]) => [k, `${v / 16}rem`]));
  const spacing = Object.fromEntries(dna.spacing.scale.map((v) => [String(v / 4), `${v / 16}rem`]));
  const preset = {
    theme: {
      extend: {
        colors,
        fontFamily: {
          display: fontStack(t.families.display).split(/,\s*/),
          sans: fontStack(t.families.body).split(/,\s*/),
          ...(t.families.ui ? { ui: fontStack(t.families.ui).split(/,\s*/) } : {}),
          ...(t.families.mono ? { mono: fontStack(t.families.mono).split(/,\s*/) } : {}),
        },
        fontSize,
        spacing,
        borderRadius: Object.fromEntries(Object.entries(dna.shape.radius).map(([k, v]) => [k, v >= 9999 ? '9999px' : `${v}px`])),
        boxShadow: dna.elevation.shadows || {},
        maxWidth: { container: `${dna.spacing.container}px` },
        letterSpacing: { display: em(t.headings.h1.letterSpacing), heading: em(t.headings.h2.letterSpacing) },
        lineHeight: { display: String(t.headings.h1.lineHeight), body: String(t.body.lineHeight) },
        transitionDuration: { DEFAULT: `${dna.motion.duration}ms` },
        transitionTimingFunction: { brand: dna.motion.easing },
      },
    },
  };
  return `// Design DNA "${dna.name}" — Tailwind CSS v3 preset. Usage: presets: [require('./tailwind.preset.js')]\nmodule.exports = ${JSON.stringify(preset, null, 2)};\n`;
}

/** W3C Design Tokens Community Group format (importable into Figma Tokens Studio, Style Dictionary...). */
export function toDtcg(dna) {
  const tokens = tokenMap(dna);
  const out = {};
  const typeOf = (k) => (k.startsWith('color-') ? 'color' : k.startsWith('font-weight') ? 'fontWeight' : k.startsWith('font-') ? 'fontFamily'
    : k.startsWith('shadow-') ? 'shadow' : k === 'duration' ? 'duration' : k.startsWith('ease') ? 'cubicBezier' : 'dimension');
  for (const [k, v] of Object.entries(tokens)) {
    const [group, ...rest] = k.split('-');
    (out[group] ||= {})[rest.join('-') || 'value'] = { $value: v, $type: typeOf(k) };
  }
  return JSON.stringify({ $description: `Design DNA ${dna.name}`, ...out }, null, 2);
}

const roleVar = (v) => (v == null ? null : String(v).startsWith('#') ? v : `var(--color-${v})`);

/** Ready-to-use component classes that encode the DNA's component recipes. */
export function toComponentsCss(dna) {
  const t = dna.typography, comp = dna.components || {}, sh = dna.shape;
  const bp = comp.buttonPrimary, bs = comp.buttonSecondary, card = comp.card, input = comp.input;
  const btnRadius = sh.buttonShape === 'pill' ? 'var(--radius-full)' : bp ? `${bp.radius >= 9999 ? 9999 : bp.radius}px` : 'var(--radius-md, 8px)';
  const upper = (x) => (x && x.transform && x.transform !== 'none' ? `\n  text-transform: ${x.transform};` : '');
  const ls = (x) => (x && x.letterSpacing ? `\n  letter-spacing: ${em(x.letterSpacing)};` : '');
  const cardBorder = card?.border ? card.border.replace(/#[0-9a-f]{6}/i, 'var(--color-border)') : dna.elevation.separation === 'borders' ? '1px solid var(--color-border)' : 'none';
  const cardShadow = card?.shadow ? (dna.elevation.shadows.md ? 'var(--shadow-md)' : card.shadow) : (dna.elevation.separation === 'shadows' && dna.elevation.shadows.md ? 'var(--shadow-md)' : 'none');
  return `${header(dna)}
/* Requires tokens.css. Class names are neutral so the same markup can be re-skinned by swapping DNAs. */

*, *::before, *::after { box-sizing: border-box; }
html { background: var(--color-background); color: var(--color-foreground); }
body {
  margin: 0;
  font-family: var(--font-body);
  font-size: var(--text-base);
  font-weight: var(--font-weight-body);
  line-height: var(--leading-body);
  -webkit-font-smoothing: antialiased;
}
h1, h2, h3, h4 { font-family: var(--font-display); color: var(--color-foreground); margin: 0; }
h1, .display {
  font-size: clamp(${Math.max(32, Math.round((t.mobile?.h1 || t.headings.h1.size * 0.6)))}px, ${Math.round((t.headings.h1.size / 1440) * 1000) / 10}vw, ${t.headings.h1.size}px);
  font-weight: var(--font-weight-display);
  line-height: var(--leading-display);
  letter-spacing: var(--tracking-display);${upper(t.headings.h1)}
}
h2 {
  font-size: clamp(${Math.max(24, Math.round(t.headings.h2.size * 0.7))}px, ${Math.round((t.headings.h2.size / 1440) * 1000) / 10}vw, ${t.headings.h2.size}px);
  font-weight: var(--font-weight-heading);
  line-height: var(--leading-heading);
  letter-spacing: var(--tracking-heading);${upper(t.headings.h2)}
}
h3 { font-size: ${t.headings.h3.size}px; font-weight: ${t.headings.h3.weight}; line-height: ${t.headings.h3.lineHeight}; letter-spacing: ${em(t.headings.h3.letterSpacing)}; }
p { margin: 0; }
.lead { font-size: var(--text-lg, 1.25rem); color: var(--color-muted-foreground); }
.muted { color: var(--color-muted-foreground); }
${t.eyebrow ? `.eyebrow {
  font-family: var(--font-ui, var(--font-body));
  font-size: ${t.eyebrow.size}px;
  font-weight: ${t.eyebrow.weight};
  letter-spacing: var(--tracking-eyebrow);
  text-transform: uppercase;
  color: var(--color-muted-foreground);
}` : `.eyebrow { font-size: var(--text-sm, 0.875rem); font-weight: 600; color: var(--color-primary); }`}

.container { max-width: var(--container); margin-inline: auto; padding-inline: var(--gutter); }
.section { padding-block: var(--section-y); }
.stack > * + * { margin-top: var(--space-4, 1rem); }

.btn {
  display: inline-flex; align-items: center; justify-content: center; gap: .5em;
  font-family: var(--font-ui, var(--font-body));
  font-size: ${bp ? `${bp.fontSize}px` : 'var(--text-sm, .875rem)'};
  font-weight: ${bp?.fontWeight || 600};${upper(bp)}${ls(bp)}
  ${bp ? `min-height: ${bp.height}px;\n  padding: ${bp.paddingY}px ${bp.paddingX}px;` : 'padding: .75em 1.25em;'}
  border-radius: ${btnRadius};
  border: 1px solid transparent;
  cursor: pointer; text-decoration: none; white-space: nowrap;
  transition: background-color var(--duration) var(--ease-brand), color var(--duration) var(--ease-brand), border-color var(--duration) var(--ease-brand), box-shadow var(--duration) var(--ease-brand), transform var(--duration) var(--ease-brand);
}
.btn-primary { background: ${roleVar(bp?.background) || 'var(--color-primary)'}; color: ${roleVar(bp?.color) || 'var(--color-primary-foreground)'};${bp?.shadow ? `\n  box-shadow: ${bp.shadow};` : ''} }
.btn-primary:hover { background: color-mix(in oklab, ${roleVar(bp?.background) || 'var(--color-primary)'} 88%, var(--color-foreground)); }
.btn-secondary {
  background: ${bs?.background && bs.background !== 'background' ? roleVar(bs.background) : 'transparent'};
  color: ${roleVar(bs?.color) || 'var(--color-foreground)'};
  border-color: ${bs?.border ? 'var(--color-border)' : 'transparent'};
}
.btn-secondary:hover { background: var(--color-muted); }
.btn:focus-visible, .input:focus-visible { outline: 2px solid var(--color-ring); outline-offset: 2px; }

.card {
  background: ${roleVar(card?.background) || 'var(--color-surface)'};
  border: ${cardBorder};
  border-radius: ${card ? `${card.radius}px` : 'var(--radius-lg, 12px)'};
  box-shadow: ${cardShadow};
  padding: ${card ? `${Math.max(card.paddingY, 16)}px ${Math.max(card.paddingX, 16)}px` : 'var(--space-6, 1.5rem)'};
}

.input {
  font: inherit;
  width: 100%;
  box-sizing: border-box;
  min-height: ${input?.height || 44}px;
  padding: 0 ${input?.paddingX || 14}px;
  background: ${roleVar(input?.background) || 'var(--color-background)'};
  color: var(--color-foreground);
  border: 1px solid var(--color-border);
  border-radius: ${input ? `${input.radius}px` : 'var(--radius-md, 8px)'};
  transition: border-color var(--duration) var(--ease-brand), box-shadow var(--duration) var(--ease-brand);
}
.input::placeholder { color: var(--color-muted-foreground); }

a { color: ${roleVar(comp.link?.color) || 'var(--color-primary)'}; text-decoration: ${comp.link?.underline ? 'underline' : 'none'}; text-underline-offset: .2em; }

.nav {
  position: ${dna.layout.nav?.position === 'fixed' || dna.layout.nav?.position === 'sticky' ? 'sticky' : 'relative'}; top: 0; z-index: 50;
  ${dna.layout.nav?.style === 'glass' ? 'background: color-mix(in oklab, var(--color-background) 70%, transparent);\n  backdrop-filter: saturate(1.4) blur(14px);' : dna.layout.nav?.style === 'transparent' ? 'background: transparent;' : 'background: var(--color-background);'}
  ${dna.layout.nav?.border ? 'border-bottom: 1px solid var(--color-border);' : ''}
}
.nav-inner { display: flex; align-items: center; justify-content: space-between; min-height: ${dna.layout.nav?.height && dna.layout.nav.height < 120 ? dna.layout.nav.height : 64}px; gap: var(--space-4, 1rem); }
${dna.effects.textGradient && dna.color.gradients[0] ? `.text-gradient { background: var(--gradient-brand); -webkit-background-clip: text; background-clip: text; color: transparent; }\n` : ''}`;
}
